#!/bin/sh
set -eu

POSTGRES_HOST="${POSTGRES_HOST:-127.0.0.1}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_DB="${POSTGRES_DB:-dags}"
POSTGRES_USER="${POSTGRES_USER:-dags}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-dags}"
BACKEND_PORT="${BACKEND_PORT:-8080}"

until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -d "$POSTGRES_DB" -U "$POSTGRES_USER" >/dev/null 2>&1; do
  sleep 1
done

export SERVER_PORT="${SERVER_PORT:-$BACKEND_PORT}"
export SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL:-jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"
export SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME:-$POSTGRES_USER}"
export SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD:-$POSTGRES_PASSWORD}"
export CHAT_MEMORY_PROVIDER="${CHAT_MEMORY_PROVIDER:-postgres}"
export CHAT_DOCUMENTS_PROVIDER="${CHAT_DOCUMENTS_PROVIDER:-pgvector}"

exec java -jar /opt/dags/backend/app.jar
