/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as SourceRouteImport } from './routes/source'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourceSourceIdRouteImport } from './routes/source.$sourceId'
import { Route as ConversationConversationIdRouteImport } from './routes/conversation.$conversationId'
import { Route as ChatDocumentRouteImport } from './routes/chat.document'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiGenerateChatRouteImport } from './routes/api/generate-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ConversationConversationIdHistoryRouteImport } from './routes/conversation.$conversationId.history'
import { Route as ChatDocumentDocumentIdRouteImport } from './routes/chat.document.$documentId'

const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceSourceIdRoute = SourceSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => SourceRoute,
} as any)
const ConversationConversationIdRoute =
  ConversationConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ConversationRoute,
  } as any)
const ChatDocumentRoute = ChatDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => ChatRoute,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateChatRoute = ApiGenerateChatRouteImport.update({
  id: '/api/generate-chat',
  path: '/api/generate-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationConversationIdHistoryRoute =
  ConversationConversationIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ConversationConversationIdRoute,
  } as any)
const ChatDocumentDocumentIdRoute = ChatDocumentDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => ChatDocumentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/briefing': typeof BriefingRoute
  '/chat': typeof ChatRouteWithChildren
  '/conversation': typeof ConversationRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/source': typeof SourceRouteWithChildren
  '/translate': typeof TranslateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-chat': typeof ApiGenerateChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/chat/document': typeof ChatDocumentRouteWithChildren
  '/conversation/$conversationId': typeof ConversationConversationIdRouteWithChildren
  '/source/$sourceId': typeof SourceSourceIdRoute
  '/chat/document/$documentId': typeof ChatDocumentDocumentIdRoute
  '/conversation/$conversationId/history': typeof ConversationConversationIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/briefing': typeof BriefingRoute
  '/chat': typeof ChatRouteWithChildren
  '/conversation': typeof ConversationRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/source': typeof SourceRouteWithChildren
  '/translate': typeof TranslateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-chat': typeof ApiGenerateChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/chat/document': typeof ChatDocumentRouteWithChildren
  '/conversation/$conversationId': typeof ConversationConversationIdRouteWithChildren
  '/source/$sourceId': typeof SourceSourceIdRoute
  '/chat/document/$documentId': typeof ChatDocumentDocumentIdRoute
  '/conversation/$conversationId/history': typeof ConversationConversationIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/briefing': typeof BriefingRoute
  '/chat': typeof ChatRouteWithChildren
  '/conversation': typeof ConversationRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/source': typeof SourceRouteWithChildren
  '/translate': typeof TranslateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-chat': typeof ApiGenerateChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/chat/document': typeof ChatDocumentRouteWithChildren
  '/conversation/$conversationId': typeof ConversationConversationIdRouteWithChildren
  '/source/$sourceId': typeof SourceSourceIdRoute
  '/chat/document/$documentId': typeof ChatDocumentDocumentIdRoute
  '/conversation/$conversationId/history': typeof ConversationConversationIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/briefing'
    | '/chat'
    | '/conversation'
    | '/history'
    | '/login'
    | '/settings'
    | '/source'
    | '/translate'
    | '/api/chat'
    | '/api/generate-chat'
    | '/api/translate'
    | '/chat/document'
    | '/conversation/$conversationId'
    | '/source/$sourceId'
    | '/chat/document/$documentId'
    | '/conversation/$conversationId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/briefing'
    | '/chat'
    | '/conversation'
    | '/history'
    | '/login'
    | '/settings'
    | '/source'
    | '/translate'
    | '/api/chat'
    | '/api/generate-chat'
    | '/api/translate'
    | '/chat/document'
    | '/conversation/$conversationId'
    | '/source/$sourceId'
    | '/chat/document/$documentId'
    | '/conversation/$conversationId/history'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/briefing'
    | '/chat'
    | '/conversation'
    | '/history'
    | '/login'
    | '/settings'
    | '/source'
    | '/translate'
    | '/api/chat'
    | '/api/generate-chat'
    | '/api/translate'
    | '/chat/document'
    | '/conversation/$conversationId'
    | '/source/$sourceId'
    | '/chat/document/$documentId'
    | '/conversation/$conversationId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  BriefingRoute: typeof BriefingRoute
  ChatRoute: typeof ChatRouteWithChildren
  ConversationRoute: typeof ConversationRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SourceRoute: typeof SourceRouteWithChildren
  TranslateRoute: typeof TranslateRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateChatRoute: typeof ApiGenerateChatRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source/$sourceId': {
      id: '/source/$sourceId'
      path: '/$sourceId'
      fullPath: '/source/$sourceId'
      preLoaderRoute: typeof SourceSourceIdRouteImport
      parentRoute: typeof SourceRoute
    }
    '/conversation/$conversationId': {
      id: '/conversation/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversation/$conversationId'
      preLoaderRoute: typeof ConversationConversationIdRouteImport
      parentRoute: typeof ConversationRoute
    }
    '/chat/document': {
      id: '/chat/document'
      path: '/document'
      fullPath: '/chat/document'
      preLoaderRoute: typeof ChatDocumentRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-chat': {
      id: '/api/generate-chat'
      path: '/api/generate-chat'
      fullPath: '/api/generate-chat'
      preLoaderRoute: typeof ApiGenerateChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$conversationId/history': {
      id: '/conversation/$conversationId/history'
      path: '/history'
      fullPath: '/conversation/$conversationId/history'
      preLoaderRoute: typeof ConversationConversationIdHistoryRouteImport
      parentRoute: typeof ConversationConversationIdRoute
    }
    '/chat/document/$documentId': {
      id: '/chat/document/$documentId'
      path: '/$documentId'
      fullPath: '/chat/document/$documentId'
      preLoaderRoute: typeof ChatDocumentDocumentIdRouteImport
      parentRoute: typeof ChatDocumentRoute
    }
  }
}

interface ChatDocumentRouteChildren {
  ChatDocumentDocumentIdRoute: typeof ChatDocumentDocumentIdRoute
}

const ChatDocumentRouteChildren: ChatDocumentRouteChildren = {
  ChatDocumentDocumentIdRoute: ChatDocumentDocumentIdRoute,
}

const ChatDocumentRouteWithChildren = ChatDocumentRoute._addFileChildren(
  ChatDocumentRouteChildren,
)

interface ChatRouteChildren {
  ChatDocumentRoute: typeof ChatDocumentRouteWithChildren
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatDocumentRoute: ChatDocumentRouteWithChildren,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ConversationConversationIdRouteChildren {
  ConversationConversationIdHistoryRoute: typeof ConversationConversationIdHistoryRoute
}

const ConversationConversationIdRouteChildren: ConversationConversationIdRouteChildren =
  {
    ConversationConversationIdHistoryRoute:
      ConversationConversationIdHistoryRoute,
  }

const ConversationConversationIdRouteWithChildren =
  ConversationConversationIdRoute._addFileChildren(
    ConversationConversationIdRouteChildren,
  )

interface ConversationRouteChildren {
  ConversationConversationIdRoute: typeof ConversationConversationIdRouteWithChildren
}

const ConversationRouteChildren: ConversationRouteChildren = {
  ConversationConversationIdRoute: ConversationConversationIdRouteWithChildren,
}

const ConversationRouteWithChildren = ConversationRoute._addFileChildren(
  ConversationRouteChildren,
)

interface SourceRouteChildren {
  SourceSourceIdRoute: typeof SourceSourceIdRoute
}

const SourceRouteChildren: SourceRouteChildren = {
  SourceSourceIdRoute: SourceSourceIdRoute,
}

const SourceRouteWithChildren =
  SourceRoute._addFileChildren(SourceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  BriefingRoute: BriefingRoute,
  ChatRoute: ChatRouteWithChildren,
  ConversationRoute: ConversationRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SourceRoute: SourceRouteWithChildren,
  TranslateRoute: TranslateRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateChatRoute: ApiGenerateChatRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
