chat:
  default-model: gemma4:e4b

spring:
  ai:
    ollama:
      base-url: http://192.168.0.13:11434
      chat:
        options:
          model: gemma4:e4b
  datasource:
    url: "jdbc:postgresql://localhost:5432/dags"
    username: "dags"
    password: "dags"
