/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'

const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/translate': typeof TranslateRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/translate': typeof TranslateRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/translate': typeof TranslateRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/translate' | '/api/translate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/translate' | '/api/translate'
  id: '__root__' | '/' | '/translate' | '/api/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TranslateRoute: typeof TranslateRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TranslateRoute: TranslateRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
